package com.example.mybatisgeneratorsample.mapper;

import com.example.mybatisgeneratorsample.entity.Todo;
import com.example.mybatisgeneratorsample.entity.TodoKey;
import com.example.mybatisgeneratorsample.example.TodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    long countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int deleteByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    Todo selectByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    int updateByPrimaryKey(Todo record);
}