package com.example.mybatisgeneratorsample.entity;

import java.util.Date;

public class Todo extends TodoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.project_id
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.title
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.description
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.status
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.priority
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.due_date
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.created_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.updated_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.project_id
     *
     * @return the value of todos.project_id
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.project_id
     *
     * @param projectId the value for todos.project_id
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.title
     *
     * @return the value of todos.title
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.title
     *
     * @param title the value for todos.title
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.description
     *
     * @return the value of todos.description
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.description
     *
     * @param description the value for todos.description
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.status
     *
     * @return the value of todos.status
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.status
     *
     * @param status the value for todos.status
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.priority
     *
     * @return the value of todos.priority
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.priority
     *
     * @param priority the value for todos.priority
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.due_date
     *
     * @return the value of todos.due_date
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.due_date
     *
     * @param dueDate the value for todos.due_date
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.created_at
     *
     * @return the value of todos.created_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.created_at
     *
     * @param createdAt the value for todos.created_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.updated_at
     *
     * @return the value of todos.updated_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.updated_at
     *
     * @param updatedAt the value for todos.updated_at
     *
     * @mbg.generated Fri Mar 28 09:34:52 JST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}